### ISSUE TITLE
missing triangle

### ISSUE THREAD

**Issue by christophegithubtts** [mapbox/earcut.hpp#109] opened 2022-12-07 10:51 UTC
Hello 
I have noticed that earcut outputs only 6 triangles instead of 7 from the following polygon
![bug](https://user-images.githubusercontent.com/27278319/206159503-2fa00714-271b-44d5-b2e3-de21fa30df61.jpg)
[bug.txt](https://github.com/mapbox/earcut.hpp/files/10175260/bug.txt)

I have also tried to offset all coordinates to make them relative to the first point but that does not solve the issue.
So i believe there is a bug which is quite surprising since the input polygon is very simple !

I hope someone can investigate this issue

**Comment by mrgreywater** [comment] 2022-12-07 11:41
This is known behavior. Earcut cleans up colinear points while triangulating.

![image](https://user-images.githubusercontent.com/2902403/206170510-8bfd3b43-edeb-42f2-a5f0-4386d12a6da5.png)

Duplicate of https://github.com/mapbox/earcut.hpp/issues/73 https://github.com/mapbox/earcut.hpp/issues/74

**Closed by mrgreywater** 2022-12-07 11:41 UTC
